# gui/strings.py — Centralized UI text for the Flet GUI.
#
# All user-facing literals live here so gui/pages and gui/components contain
# layout/logic, not text. This is step 1 of language-toggle support: pure
# decoupling — only Chinese text for now, no English translations yet.
#
# Usage:
#   from ..strings import t            # from gui/pages/*.py or gui/components/*.py
#   from gui.strings import t          # from app.py
#   ft.Text(t("landing.button_start_convert"))
#   ft.Text(t("common.loaded_file", name=path.name))

from __future__ import annotations

STRINGS: dict[str, str] = {
    # ── common / shared across pages ────────────────────────────────────────
    "common.cancel": "取消",
    "common.delete": "删除",
    "common.close": "关闭",
    "common.confirm": "确认",
    "common.open_score": "打开乐谱",
    "common.jianpu_edit": "简谱编辑",
    "common.tooltip_play_midi": "播放 MIDI",
    "common.tooltip_refresh_list": "刷新列表",
    "common.tooltip_toggle_select_all": "全选 / 全不选",
    "common.tooltip_delete_file": "删除此文件",
    "common.tooltip_zoom_in": "放大",
    "common.tooltip_zoom_out": "缩小",
    "common.empty_score_hint": "请先识别乐谱文件\n或点击刷新按钮",
    "common.loaded_file": "已加载: {name}",
    "common.export_failed_exc": "导出失败: {exc}",
    "common.open_dir_failed": "无法打开目录: {exc}",
    "common.midi_open_failed": "无法打开 MIDI 文件: {exc}",
    "common.midi_not_found": "未找到 MIDI 文件：{name}",

    # ── app.py ───────────────────────────────────────────────────────────────
    "app.nav_landing": "乐谱识别",
    "app.nav_editor": "简谱预览",
    "app.nav_score_preview": "五线谱预览",
    "app.nav_about": "关于",
    "app.window_title": "SumisoraOMR",
    "app.tooltip_hide_label": "隐藏标签",
    "app.tooltip_show_label": "显示标签",
    "app.tooltip_theme_toggle": "切换明暗主题",
    "app.tooltip_maximize": "最大化 / 还原",
    "app.tooltip_minimize": "最小化",
    "app.tooltip_close": "关闭",
    "app.title_bar": "SumisoraOMR  v{version}",
    "app.snack_error": "错误: {message}",
    "app.snack_done_default": "完成",
    "app.single_instance_title": "Sumisora OMR",
    "app.single_instance_body": "Sumisora OMR 已在运行中。\n\n请查看任务栏。",

    # ── gui/pages/about_page.py ─────────────────────────────────────────────
    "about.subtitle": "五线谱识别与简谱生成工具",
    "about.author_label": "作者",
    "about.homepage_label": "项目主页",
    "about.license_label": "开源许可证 (AGPL-3.0)",

    # ── gui/pages/editor_page.py ────────────────────────────────────────────
    "editor.error_jianpu_ly_failed": "jianpu-ly 转换失败，请确认安装",
    "editor.error_lilypond_render_failed": "LilyPond 渲染失败，请检查文件语法",
    "editor.error_pdf_unparseable": "PDF 无法解析",
    "editor.error_render_exc": "渲染出错: {exc}",
    "editor.tooltip_re_render": "重新渲染简谱",
    "editor.tooltip_fit": "适应",
    "editor.placeholder_select_file": "请先在首页选择并转换文件，或在此页打开对应图像/简谱文件",
    "editor.rendering": "渲染中…",
    "editor.placeholder_click_jianpu": "点击「简谱」生成渲染预览",
    "editor.error_pdf_render_failed": "PDF 无法渲染",
    "editor.error_load_failed_exc": "加载失败: {exc}",
    "editor.tooltip_back_to_preview": "返回简谱预览",
    "editor.file_picker_open_image": "打开图像文件（PDF / PNG / JPG）",
    "editor.error_no_jianpu_loaded": "未加载简谱文件",
    "editor.render_failed_default": "渲染失败",

    # ── gui/pages/jianpu_preview_page.py ────────────────────────────────────
    "jianpu_preview.tooltip_export_checked": "导出已勾选的简谱",
    "jianpu_preview.tooltip_delete_checked": "删除已勾选的简谱",
    "jianpu_preview.section_title": "简谱文件",
    "jianpu_preview.button_export": "导出简谱",
    "jianpu_preview.button_re_render": "重新渲染",
    "jianpu_preview.tooltip_re_render_from_text": "从编辑器文本重新生成简谱 PDF（无需重跑识别）",
    "jianpu_preview.delete_dialog_title": "删除简谱文件",
    "jianpu_preview.delete_dialog_body": "将永久删除：{name} 及其关联的 MIDI 和编辑文本。",
    "jianpu_preview.batch_delete_dialog_title": "批量删除简谱文件",
    "jianpu_preview.batch_delete_dialog_body": "将永久删除已勾选的 {n} 个简谱文件及其关联文件。",
    "jianpu_preview.error_select_for_render": "请先选择要重新渲染的简谱文件",
    "jianpu_preview.error_txt_not_found": "未找到对应的简谱文本文件：{name}",
    "jianpu_preview.error_re_render_jianpu_ly": "重新渲染失败：jianpu-ly 转换出错",
    "jianpu_preview.error_re_render_lilypond": "重新渲染失败：LilyPond 未能生成 PDF",
    "jianpu_preview.re_render_done": "重新渲染完成 → {name}",
    "jianpu_preview.re_render_error": "重新渲染出错: {exc}",
    "jianpu_preview.error_select_for_export": "请先选择要导出的简谱文件",
    "jianpu_preview.error_checked_for_export": "请先勾选要导出的简谱文件",
    "jianpu_preview.export_single_done": "已导出 → {name}",
    "jianpu_preview.file_picker_export": "导出简谱 PDF",
    "jianpu_preview.dir_picker_export": "选择导出目标目录",
    "jianpu_preview.export_done_counts": "导出完成：{success} 个成功，{fail} 个失败",
    "jianpu_preview.export_done_summary": "已导出 {n} 个简谱至 {dest}",

    # ── gui/pages/landing_page.py ───────────────────────────────────────────
    "landing.suffix_download_needed": "（需下载）",
    "landing.option_auto": "自动选择（推荐）{suffix}",
    "landing.option_audiveris": "Audiveris（启发式算法）",
    "landing.option_homr": "Homr（深度学习）{suffix}",
    "landing.label_omr_engine": "OMR 引擎",
    "landing.tooltip_omr_engine": "自动选择会根据输入格式与图像质量决定使用 Audiveris 还是 Homr",
    "landing.label_sr_engine": "超分辨率算法",
    "landing.option_waifu2x": "waifu2x（线条画）",
    "landing.option_realesrgan": "Real-ESRGAN（anime，默认）",
    "landing.tooltip_sr_engine": "低分辨率图片在识别前会先放大增强；两种算法适合不同风格的图源",
    "landing.label_concurrency": "并发处理数",
    "landing.option_concurrency_1": "1（顺序，低配推荐）",
    "landing.option_concurrency_2": "2 个并行",
    "landing.option_concurrency_4": "4 个并行",
    "landing.option_concurrency_auto": "自动（按 CPU 核数）",
    "landing.tooltip_concurrency": "同时转换多个文件可加速批量处理；内存或显存不足时请保持 1",
    "landing.button_start_convert": "开始转换",
    "landing.button_open_output_dir": "打开输出目录",
    "landing.button_download_models": "下载模型文件",
    "landing.button_delete_models": "删除模型文件",
    "landing.section_convert_options": "转换选项",
    "landing.section_homr_models": "HOMR 模型管理",
    "landing.download_dialog_title": "需要下载 HOMR 模型权重",
    "landing.download_dialog_body": "使用 HOMR 引擎可以支持图片格式的乐谱识别。\n需要下载约 292 MB 模型权重。",
    "landing.button_not_now": "暂不下载",
    "landing.button_download_now": "立即下载",
    "landing.button_start_convert_with_count": "开始转换（{n}）",
    "landing.models_deleted": "已删除 {n} 个模型文件。",
    "landing.delete_models_dialog_title": "确认删除模型文件",
    "landing.delete_models_dialog_body": "将删除全部 HOMR 模型权重文件（约 292 MB）。\n下次使用 HOMR 引擎时需要重新下载。",
    "landing.error_select_at_least_one": "请先勾选至少一个乐谱文件。",
    "landing.existing_outputs_warning": "以下 {n} 个文件已存在输出：",
    "landing.existing_outputs_more": "  …等另外 {n} 个",
    "landing.checkbox_skip_duplicates": "跳过重复文件（不重新识别）",
    "landing.convert_dialog_title": "转换 {n} 个文件",
    "landing.running_omr": "正在运行 OMR 识别…",
    "landing.log_gpu_crash_retry": "[homr] GPU 模式发生崩溃，正在以 GPU 模式重试…",
    "landing.log_gpu_crash_fallback_cpu": "[homr] GPU 模式再次崩溃，已回退到 CPU 模式重试…",
    "landing.worker_crash_error": "Worker 进程异常退出（{code}）：{detail}",
    "landing.worker_crash_no_detail": "无详情",
    "landing.done_message": "完成。",
    "landing.log_worker_assign": "[W{worker}] 分配: {names}",
    "landing.log_error_prefix": "{prefix}错误: {err}",
    "landing.log_worker_crash": "[W{worker}] 进程异常退出 {hint}",
    "landing.all_workers_failed": "所有 Worker 进程均失败，请检查日志。",
    "landing.summary_success_part": "{n} 个成功",
    "landing.summary_fail_part": "{n} 个失败",
    "landing.summary_skipped_part": "{n} 个已跳过",
    "landing.summary_done_prefix": "完成：",
    "landing.summary_done_fallback": "完成",
    "landing.stat_success": "✓ 成功 {n}",
    "landing.stat_failed": "✗ 失败 {n}",
    "landing.stat_total": "总共 {n} 个文件",
    "landing.section_success": "成功",
    "landing.detail_image_type": "识别为{kind}",
    "landing.detail_engine_used": "使用 {engine} 引擎",
    "landing.detail_success_fallback": "转换成功",
    "landing.list_item_success": "  ✓  {name}",
    "landing.list_item_detail": "       {detail}",
    "landing.section_failed": "失败",
    "landing.list_item_failed": "  ✗  {name}",
    "landing.list_item_reason": "       原因：{reason}",
    "landing.result_dialog_title": "识别结果",
    "landing.button_view_jianpu": "查看简谱",
    "landing.unknown_reason": "未知原因",
    "landing.unknown_error": "未知错误",
    "landing.unknown_file": "未知",
    "landing.names_preview_more": " 等 {n} 个",
    "landing.process_error": "进程错误",
    "landing.crash_hint_code": "（代码 {rc}）",
    "landing.crash_hint_tail": "：{tail}",

    # ── gui/pages/score_preview_page.py ─────────────────────────────────────
    "score_preview.tooltip_export_checked": "导出已勾选的五线谱 PDF",
    "score_preview.tooltip_delete_checked": "删除已勾选的五线谱",
    "score_preview.section_title": "五线谱文件",
    "score_preview.button_export": "导出乐谱",
    "score_preview.button_transpose": "乐谱移调",
    "score_preview.delete_dialog_title": "删除五线谱文件",
    "score_preview.delete_dialog_body": "将永久删除：{name}",
    "score_preview.batch_delete_dialog_title": "批量删除五线谱文件",
    "score_preview.batch_delete_dialog_body": "将永久删除已勾选的 {n} 个五线谱文件。",
    "score_preview.status_rendering": "渲染中: {name}...",
    "score_preview.error_preview_render_failed": "预览渲染失败：LilyPond 不可用或文件有误",
    "score_preview.error_render_failed_exc": "渲染失败: {exc}",
    "score_preview.error_select_score_first": "请先选择乐谱文件。",
    "score_preview.file_picker_export": "导出五线谱 PDF",
    "score_preview.export_done": "导出完成 → {dest}",
    "score_preview.error_export_failed": "导出失败：无法生成五线谱 PDF，请检查 LilyPond 是否可用。",
    "score_preview.error_select_for_export": "请先勾选要导出的五线谱文件。",
    "score_preview.dir_picker_export": "选择导出目标目录",
    "score_preview.batch_export_start": "批量导出 {n} 个文件...",
    "score_preview.batch_export_progress": "导出中... {done}/{total}",
    "score_preview.batch_export_done_counts": "导出完成：{success} 个成功，{fail} 个失败",
    "score_preview.batch_export_done_summary": "已导出 {n} 个五线谱 PDF 至 {dest}",

    # ── gui/pages/transposer_page.py ────────────────────────────────────────
    "transposer.dir_recent": "最近",
    "transposer.dir_up": "向上",
    "transposer.dir_down": "向下",
    "transposer.interval_default": "纯一度",
    "transposer.degree_default": "三度",
    "transposer.label_interval": "音程",
    "transposer.label_from_key": "原调",
    "transposer.label_to_key": "目标调",
    "transposer.arrow": "→",
    "transposer.label_degree": "度数",
    "transposer.mode_interval": "按音程",
    "transposer.mode_key": "按调",
    "transposer.mode_chromatic": "全音移调",
    "transposer.advanced_options_title": "高级选项",
    "transposer.fallback_interval": "纯四度",
    "transposer.quick_label_direction": "方向",
    "transposer.checkbox_transpose_key_signature": "移调调号",
    "transposer.checkbox_transpose_key_signature_adv": "同时移调调号",
    "transposer.button_export_transposed": "导出移调乐谱",
    "transposer.button_export_original": "导出原调乐谱",
    "transposer.tooltip_back_to_score_preview": "返回五线谱预览",
    "transposer.button_open_score_dir": "打开乐谱目录",
    "transposer.section_title": "移调功能",
    "transposer.label_transposed_col": "移调后",
    "transposer.status_open_score_first": "请先打开乐谱文件。",
    "transposer.status_wait_preview_save": "请先等待移调预览生成后再保存。",
    "transposer.status_saved": "已保存移调版乐谱 → {name}",
    "transposer.status_save_failed": "保存失败: {exc}",
    "transposer.file_picker_open_musicxml": "打开乐谱文件（MusicXML）",
    "transposer.status_preview_only": "预览: {name}（仅预览，移调需 MXL 格式）",
    "transposer.status_detected_key": "检测到原调: {key}",
    "transposer.status_key_detect_failed": "调号检测失败: {exc}",
    "transposer.status_convert_or_open_first": "请先在首页转换文件或打开乐谱。",
    "transposer.status_transpose_done": "移调完成 → {name}",
    "transposer.status_transpose_failed": "移调失败: {exc}",
    "transposer.status_wait_preview_export": "请先等待移调预览生成后再导出。",
    "transposer.file_picker_export_transposed": "导出移调版 PDF",
    "transposer.status_open_original_first": "请先加载原调乐谱后再导出。",
    "transposer.file_picker_export_original": "导出原调乐谱 PDF",
    "transposer.export_done": "导出完成 → {dest}",
    "transposer.export_failed_transposed": "导出失败：无法生成五线谱 PDF，请检查 LilyPond / musicxml2ly 是否可用。",
    "transposer.export_failed_original": "导出失败：无法生成原调乐谱 PDF，请检查 LilyPond / musicxml2ly 是否可用。",
    "transposer.status_preview_render_failed": "预览渲染失败: {exc}",

    # ── gui/components/pdf_viewer.py ────────────────────────────────────────
    "pdf_viewer.page_placeholder": "—",
    "pdf_viewer.tooltip_prev_page": "上一页",
    "pdf_viewer.tooltip_next_page": "下一页",
    "pdf_viewer.tooltip_reset_zoom": "复位缩放",
    "pdf_viewer.no_file": "暂无文件",
    "pdf_viewer.error_render_failed": "PDF 无法渲染（文件可能已损坏或格式不受支持）",
    "pdf_viewer.page_label": "{current} / {total}",

    # ── gui/components/file_sidebar.py ──────────────────────────────────────
    "file_sidebar.tooltip_delete_checked": "删除已勾选的文件",
    "file_sidebar.section_title": "文件列表",
    "file_sidebar.tooltip_add_folder": "添加文件夹",
    "file_sidebar.tooltip_add_file": "添加文件",
    "file_sidebar.empty_hint": "还没有乐谱文件",
    "file_sidebar.button_add_file": "添加文件",
    "file_sidebar.empty_supported_formats": "支持 PDF / PNG / JPG\n也可直接放入 Input 文件夹",
    "file_sidebar.delete_dialog_title": "删除文件",
    "file_sidebar.delete_dialog_body": "将从 Input 文件夹中永久删除：\n{name}",
    "file_sidebar.tooltip_remove_from_input": "从 Input 文件夹删除",
    "file_sidebar.batch_delete_body_mixed": "将永久删除 {m} 个 Input 文件夹中的文件，另有 {n} 个仅从列表移除。",
    "file_sidebar.batch_delete_body_all_input": "将永久删除 {n} 个 Input 文件夹中的文件。",
    "file_sidebar.batch_delete_body_list_only": "将从列表移除 {n} 个文件（不删除磁盘文件）。",
    "file_sidebar.batch_delete_dialog_title": "批量删除文件",
    "file_sidebar.file_picker_select_score": "选择乐谱文件",
    "file_sidebar.folder_picker_select": "选择包含乐谱文件的文件夹",
    "file_sidebar.import_preparing": "准备中…",
    "file_sidebar.import_dialog_title": "导入 {n} 个文件",
    "file_sidebar.import_progress": "({index}/{total})  {name}",
    "file_sidebar.import_organizing": "正在整理 {n} 个文件…",

    # ── gui/components/model_download_dialog.py ────────────────────────────
    "model_download.source_auto_label": "自动选择",
    "model_download.source_auto_desc": "自动检测延迟最低的可用源（推荐）",
    "model_download.source_modelscope_label": "ModelScope",
    "model_download.source_modelscope_desc": "ModelScope CDN — 大陆访问优先",
    "model_download.source_github_label": "GitHub Releases",
    "model_download.source_github_desc": "GitHub — 海外访问优先",
    "model_download.dialog_title": "HOMR 模型权重",
    "model_download.label_source": "下载源",
    "model_download.intro_text": "选择下载源后点击「开始下载」。HOMR 模型约 292 MB（GitHub 源以压缩包分发，实际下载约 265 MB），下载到 models/ 目录。",
    "model_download.picker_dialog_title": "下载 HOMR 模型权重",
    "model_download.button_start_download": "开始下载",
    "model_download.source_status_testing": "当前源: 测试中…",
    "model_download.file_status_preparing": "准备中…",
    "model_download.progress_initial": "0 / ? MB",
    "model_download.downloading_dialog_title": "正在下载 HOMR 模型权重",
    "model_download.error_dialog_title": "下载出错",
    "model_download.button_retry": "重试",
    "model_download.file_progress": "下载中 ({index}/{total}): {name}",
    "model_download.file_size_progress": "{done} / {total} MB ({pct}%)",
    "model_download.file_size_progress_no_total": "{done} MB",
    "model_download.overall_progress": "{done} / {total} MB",
    "model_download.source_auto_modelscope": "ModelScope",
    "model_download.source_auto_github_fallback": "GitHub（备用）",
    "model_download.source_label_modelscope": "ModelScope",
    "model_download.source_label_github": "GitHub",
    "model_download.source_status": "当前源: {label}",
    "model_download.error_no_source": "下载失败 — 请检查网络连接",
    "model_download.error_hash_mismatch": "权重文件校验失败：{exc}",
    "model_download.error_generic": "下载失败：{exc}",

    # ── gui/components/progress_overlay.py ──────────────────────────────────
    "progress_overlay.button_show_log": "显示详细日志",
    "progress_overlay.default_message": "处理中…",
    "progress_overlay.elapsed_initial": "00:00",
    "progress_overlay.button_hide_log": "隐藏详细日志",
    "progress_overlay.error_status": "错误：{message}",
    "progress_overlay.done_default": "完成",

    # ── gui/components/jianpu_editor.py ─────────────────────────────────────
    "jianpu_editor.title": "简谱编辑器",
    "jianpu_editor.tooltip_undo": "撤销 (Ctrl+Z)",
    "jianpu_editor.tooltip_redo": "重做 (Ctrl+Y)",
    "jianpu_editor.button_save": "保存",
    "jianpu_editor.button_export_pdf": "导出PDF",
    "jianpu_editor.tooltip_export_pdf": "将当前简谱文件通过 LilyPond 渲染为 PDF",
    "jianpu_editor.tooltip_symbol_panel": "简谱符号速查",
    "jianpu_editor.toggle_jianpu": "简谱",
    "jianpu_editor.toggle_original": "原图",
    "jianpu_editor.hint_no_file": "尚未加载简谱文件…",
    "jianpu_editor.symbol_section_notes": "── 音符",
    "jianpu_editor.symbol_notes_row": "1 2 3 4 5 6 7",
    "jianpu_editor.symbol_notes_desc": "Do Re Mi Fa Sol La Si",
    "jianpu_editor.symbol_rest_row": "0",
    "jianpu_editor.symbol_rest_desc": "休止符",
    "jianpu_editor.symbol_accidental_row": "#1  b3",
    "jianpu_editor.symbol_accidental_desc": "升 Do / 降 Mi（写在数字前）",
    "jianpu_editor.symbol_high_octave_row": "1'  1''",
    "jianpu_editor.symbol_high_octave_desc": "高八度 / 超高八度",
    "jianpu_editor.symbol_low_octave_row": "1,  1,,",
    "jianpu_editor.symbol_low_octave_desc": "低八度 / 超低八度",
    "jianpu_editor.symbol_section_duration": "── 时值",
    "jianpu_editor.symbol_duration_row_1": "1",
    "jianpu_editor.symbol_duration_desc_1": "四分音符（1 拍）",
    "jianpu_editor.symbol_duration_row_2": "1 -",
    "jianpu_editor.symbol_duration_desc_2": "二分音符（2 拍）",
    "jianpu_editor.symbol_duration_row_3": "1 - - -",
    "jianpu_editor.symbol_duration_desc_3": "全音符（4 拍）",
    "jianpu_editor.symbol_duration_row_4": "q1",
    "jianpu_editor.symbol_duration_desc_4": "八分音符（½ 拍）",
    "jianpu_editor.symbol_duration_row_5": "s1",
    "jianpu_editor.symbol_duration_desc_5": "十六分音符（¼ 拍）",
    "jianpu_editor.symbol_duration_row_6": "d1",
    "jianpu_editor.symbol_duration_desc_6": "三十二分音符（⅛ 拍）",
    "jianpu_editor.symbol_duration_row_7": "1.",
    "jianpu_editor.symbol_duration_desc_7": "附点四分（1.5 拍）",
    "jianpu_editor.symbol_duration_row_8": "q1.",
    "jianpu_editor.symbol_duration_desc_8": "附点八分（0.75 拍）",
    "jianpu_editor.symbol_section_structure": "── 结构",
    "jianpu_editor.symbol_structure_row_1": "|",
    "jianpu_editor.symbol_structure_desc_1": "小节线",
    "jianpu_editor.symbol_structure_row_2": "title=曲名",
    "jianpu_editor.symbol_structure_desc_2": "标题（文件头部）",
    "jianpu_editor.symbol_structure_row_3": "1=C  1=G",
    "jianpu_editor.symbol_structure_desc_3": "调号（大调，1=主音）",
    "jianpu_editor.symbol_structure_row_4": "6=A  6=D",
    "jianpu_editor.symbol_structure_desc_4": "调号（小调，6=主音）",
    "jianpu_editor.symbol_structure_row_5": "4/4,8",
    "jianpu_editor.symbol_structure_desc_5": "拍号（分母=最小时值）",
    "jianpu_editor.symbol_section_polyphony": "── 多声部",
    "jianpu_editor.symbol_polyphony_row_1": "NextPart",
    "jianpu_editor.symbol_polyphony_desc_1": "分隔声部；每个声部单独渲染",
    "jianpu_editor.symbol_polyphony_row_2": "NextPart  4/4,8  ...",
    "jianpu_editor.symbol_polyphony_desc_2": "换声部后必须立即重写拍号",
    "jianpu_editor.symbol_polyphony_row_3": "声部1 / NextPart\n4/4,8 / 声部2",
    "jianpu_editor.symbol_polyphony_desc_3": "同组声部并排显示在同一行谱上",
    "jianpu_editor.title_dirty_suffix": " *",
    "jianpu_editor.error_read_failed": "# 文件读取失败: {exc}",
    "jianpu_editor.log_saved": "已保存: {name}",
    "jianpu_editor.log_save_failed": "保存失败: {exc}",
    "jianpu_editor.error_export_no_file": "导出失败：请先加载简谱文件",
    "jianpu_editor.log_save_failed_pre_export": "保存失败（导出前）: {exc}",
    "jianpu_editor.dir_picker_export_pdf": "选择 PDF 导出目录",
    "jianpu_editor.log_generating_ly": "正在生成 LilyPond 中间文件: {name}",
    "jianpu_editor.error_jianpu_ly_failed": "jianpu-ly 转换失败，请确认 LilyPond 与 jianpu-ly.py 已安装",
    "jianpu_editor.log_rendering_pdf": "正在渲染 PDF…",
    "jianpu_editor.log_pdf_exported": "PDF 已导出: {path}",
    "jianpu_editor.error_pdf_render_failed": "PDF 渲染失败，请检查 LilyPond 安装",
    "jianpu_editor.error_export_exc": "导出 PDF 出错: {exc}",
}


def t(key: str, **kwargs: object) -> str:
    """Look up a UI string by key and substitute any named placeholders."""
    text = STRINGS[key]
    return text.format(**kwargs) if kwargs else text
